"""initial_schema

Revision ID: 8a730ea64e8c
Revises: 
Create Date: 2026-05-12 10:16:30.446008

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a730ea64e8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('sensitivity_hypertension', sa.Boolean(), nullable=False),
    sa.Column('sensitivity_hypotension', sa.Boolean(), nullable=False),
    sa.Column('sensitivity_joint_pain', sa.Boolean(), nullable=False),
    sa.Column('sensitivity_headaches', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles'))
    )
    op.create_table('weather_records',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('kp_index', sa.Float(), nullable=False),
    sa.Column('temp_delta', sa.Float(), nullable=False),
    sa.Column('pressure_delta', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_records')),
    sa.UniqueConstraint('city', 'forecast_date', name='uq_weather_city_date')
    )
    with op.batch_alter_table('weather_records', schema=None) as batch_op:
        batch_op.create_index('ix_weather_city_date', ['city', 'forecast_date'], unique=False)

    op.create_table('diary_entries',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('user_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('wellbeing_rating', sa.Integer(), nullable=False),
    sa.Column('symptoms', sa.JSON(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('weather_pressure', sa.Float(), nullable=True),
    sa.Column('weather_kp_index', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_diary_entries_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diary_entries'))
    )
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diary_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_diary_entries_user_id'), ['user_id'], unique=False)

    op.create_table('risk_scores',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('user_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('weather_record_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_risk_scores_user_id_user_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weather_record_id'], ['weather_records.id'], name=op.f('fk_risk_scores_weather_record_id_weather_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores'))
    )
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_scores_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_scores_weather_record_id'), ['weather_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_scores_weather_record_id'))
        batch_op.drop_index(batch_op.f('ix_risk_scores_user_id'))

    op.drop_table('risk_scores')
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diary_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_diary_entries_entry_date'))

    op.drop_table('diary_entries')
    with op.batch_alter_table('weather_records', schema=None) as batch_op:
        batch_op.drop_index('ix_weather_city_date')

    op.drop_table('weather_records')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
